petnames/config/routes.rb
Rails.application.routes.draw do
  resources :petnames
  root 'petnames#index'

end

petnames/app/models/petname.rb
class Petname < ActiveRecord::Base
  has_one :species
  
  validates :name, presence: true, length: 1..26
  validates :species, presence: true

end

petnames/app/models/species.rb
class Species < ActiveRecord::Base
  belongs_to :petname
end

petnames/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

petnames/app/controllers/petnames_controller.rb
class PetnamesController < ApplicationController
  before_action :set_petname, only: [:show, :edit, :update, :destroy]

  # GET /petnames
  # GET /petnames.json
  def index
    @petnames = Petname.all
  end

  # GET /petnames/1
  # GET /petnames/1.json
  def show
  end

  # GET /petnames/new
  def new
    @petname = Petname.new
  end

  # GET /petnames/1/edit
  def edit
  end

  # POST /petnames
  # POST /petnames.json
  def create
    @petname = Petname.new(petname_params)

    respond_to do |format|
      if @petname.save
        format.html { redirect_to @petname, notice: 'Petname was successfully created.' }
        format.json { render :show, status: :created, location: @petname }
      else
        format.html { render :new }
        format.json { render json: @petname.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /petnames/1
  # PATCH/PUT /petnames/1.json
  def update
    respond_to do |format|
      if @petname.update(petname_params)
        format.html { redirect_to @petname, notice: 'Petname was successfully updated.' }
        format.json { render :show, status: :ok, location: @petname }
      else
        format.html { render :edit }
        format.json { render json: @petname.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /petnames/1
  # DELETE /petnames/1.json
  def destroy
    @petname.destroy
    respond_to do |format|
      format.html { redirect_to petnames_url, notice: 'Petname was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_petname
      @petname = Petname.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def petname_params
      params.require(:petname).permit(:name)
    end
end

petnames/app/helpers/application_helper.rb
module ApplicationHelper
end

petnames/app/helpers/petnames_helper.rb
module PetnamesHelper
end

petnames/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Petnames</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

petnames/app/views/petnames/_form.html.erb
<%= form_for(@petname) do |f| %>
  <% if @petname.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@petname.errors.count, "error") %> prohibited this petname from being saved:</h2>

      <ul>
      <% @petname.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

petnames/app/views/petnames/edit.html.erb
<h1>Editing Petname</h1>

<%= render 'form' %>

<%= link_to 'Show', @petname %> |
<%= link_to 'Back', petnames_path %>

petnames/app/views/petnames/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Petnames List</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @petnames.each do |petname| %>
      <tr id="<%=dom_id(petname) %>">
        <td><%= petname.name %></td>
        <td><%= link_to 'Show', petname %></td>
        <td><%= link_to 'Edit', edit_petname_path(petname) %></td>
        <td><%= link_to 'Destroy', petname, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Petname', new_petname_path %>

petnames/app/views/petnames/new.html.erb
<h1>New Petname</h1>

<%= render 'form' %>

<%= link_to 'Back', petnames_path %>

petnames/app/views/petnames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @petname.name %>
</p>

<%= link_to 'Edit', edit_petname_path(@petname) %> |
<%= link_to 'Back', petnames_path %>